name: celmouse

packages:
  - mobile
  - desktop
  - packages/**
  - plugins/**

ignore:
  - "*example*"

scripts:
  protocol:
    run: melos exec --scope="*protocol*" -- dart run build_runner build --delete-conflicting-outputs