name: _
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  ## Packages
  - packages/protocol/keyboard_protocol
  - packages/protocol/mouse_protocol
  - packages/protocol/protocol
  - packages/protocol/protocol_interface